### PR TITLE
Add setting for default block type

### PR DESCRIPTION
**Pull request by GrahamSH-LLK**

### CODE REVIEW

**Review by jacob-g — CHANGES_REQUESTED** [review]
Instead do this with a `$wg` variable in LocalSettings.php and modify the parser hook accordingly.

**Comment by GrahamSH-LLK** [comment]
> Instead do this with a `$wg` variable in LocalSettings.php and modify the parser hook accordingly.

Got it. It would be cool if we could somehow do this all server-side 🤔

**Comment by Kenny2github** [comment]
Closing in favor of #8

**Comment by GrahamSH-LLK** [comment]
> Closing in favor of #8

Thanks!

**Pull request closed without merging**
